name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secretsDOCKER_HUB_TOKEN }}" |
        echo "${{ secretsDOCKER_HUB_TOKEN }}" | docker login -u "${{ secretsDOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build . --file Dockerfile --tag docker.io/${{ secretsDOCKER_HUB_USERNAME }}/${{ secretsDOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
        docker push docker.io/${{ secretsDOCKER_HUB_USERNAME }}/${{ secretsDOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
